### ISSUE TITLE
Login: Internal Server Error

### ISSUE THREAD

**Issue by hubortje** [wger-project/docker#112]
Hey there,

when I'm trying to log in via the web-frontend, I'm greeted by a INTERNAL SERVER ERROR message.
The homepage works without a problem.

It seems I've got permission issues, but before I just run out and wildly start throwing out permissions, I wanted to ask, what could be the issue at hand?

```
web-1  |   File "/home/wger/src/manage.py", line 24, in <module>
web-1  |     execute_from_command_line(sys.argv)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
web-1  |     utility.execute()
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
web-1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/management/base.py", line 412, in run_from_argv
web-1  |     self.execute(*args, **cmd_options)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/management/base.py", line 458, in execute
web-1  |     output = self.handle(*args, **options)
web-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 209, in handle
web-1  |     collected = self.collect()
web-1  |                 ^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 135, in collect
web-1  |     handler(path, prefixed_path, storage)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 368, in copy_file
web-1  |     if not self.delete_file(path, prefixed_path, source_storage):
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 322, in delete_file
web-1  |     self.storage.delete(prefixed_path)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/files/storage/filesystem.py", line 158, in delete
web-1  |     os.remove(name)
web-1  | PermissionError: [Errno 13] Permission denied: '/home/wger/static/scss/palette.pdf'
web-1  | Performing database migrations
web-1  | INFO 2024-12-02 23:49:54,565 apps AXES: BEGIN version 7.0.0, blocking by ip_address
web-1  | System check identified some issues:
web-1  | 
web-1  | WARNINGS:
web-1  | ?: (wger.W002) exercises without translations
web-1  | 	HINT: There are 9 exercises without translations, this will cause problems! You can output or delete them with "python manage.py exercises-health-check --help"
web-1  | Operations to perform:
web-1  |   Apply all migrations: actstream, auth, authtoken, axes, config, contenttypes, core, easy_thumbnails, exercises, gallery, gym, mailer, manager, measurements, nutrition, sessions, sites, weight
web-1  | Running migrations:
web-1  |   No migrations to apply.
web-1  |   Your models in app(s): 'exercises', 'nutrition' have changes that are not yet reflected in a migration, and so won't be applied.
web-1  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
web-1  | INFO 2024-12-02 23:49:57,661 apps AXES: BEGIN version 7.0.0, blocking by ip_address
web-1  | System check identified some issues:
web-1  | 
web-1  | WARNINGS:
web-1  | ?: (wger.W002) exercises without translations
web-1  | 	HINT: There are 9 exercises without translations, this will cause problems! You can output or delete them with "python manage.py exercises-health-check --help"
web-1  | Set site URL to localhost
web-1  | Using gunicorn...
web-1  | [2024-12-02 22:49:59 +0000] [57] [INFO] Starting gunicorn 23.0.0
web-1  | [2024-12-02 22:49:59 +0000] [57] [INFO] Listening at: http://0.0.0.0:8000 (57)
web-1  | [2024-12-02 22:49:59 +0000] [57] [INFO] Using worker: sync
web-1  | [2024-12-02 22:49:59 +0000] [58] [INFO] Booting worker with pid: 58
web-1  | INFO 2024-12-02 23:50:00,197 apps AXES: BEGIN version 7.0.0, blocking by ip_address
web-1  | [2024-12-02 23:51:30 +0100] [58] [ERROR] Error handling request /en/user/login
web-1  | Traceback (most recent call last):
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
web-1  |     response = response.render()
web-1  |                ^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/response.py", line 114, in render
web-1  |     self.content = self.rendered_content
web-1  |                    ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
web-1  |     return template.render(context, self._request)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
web-1  |     return self.template.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 175, in render
web-1  |     return self._render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
web-1  |     return self.nodelist.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
web-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
web-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
web-1  |     return self.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
web-1  |     return compiled_parent._render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
web-1  |     return self.nodelist.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
web-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
web-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
web-1  |     return self.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/loader_tags.py", line 157, in render
web-1  |     return compiled_parent._render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 167, in _render
web-1  |     return self.nodelist.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 1005, in render
web-1  |     return SafeString("".join([node.render_annotated(context) for node in self]))
web-1  |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/template/base.py", line 966, in render_annotated
web-1  |     return self.render(context)
web-1  |            ^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/templatetags/compress.py", line 160, in render
web-1  |     return self.render_compressed(
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/templatetags/compress.py", line 131, in render_compressed
web-1  |     rendered_output = compressor.output(mode, forced=forced, basename=file_basename)
web-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/js.py", line 49, in output
web-1  |     ret.append(subnode.output(*args, **kwargs))
web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/js.py", line 51, in output
web-1  |     return super().output(*args, **kwargs)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/base.py", line 374, in output
web-1  |     return self.handle_output(mode, filtered_output, forced, basename)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/base.py", line 382, in handle_output
web-1  |     return output_func(mode, content, forced, basename)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/base.py", line 393, in output_file
web-1  |     self.storage.save(new_filepath, ContentFile(content.encode(self.charset)))
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/compressor/storage.py", line 52, in save
web-1  |     temp_filename = super().save(filename, content)
web-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/files/storage/base.py", line 49, in save
web-1  |     name = self._save(name, content)
web-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/files/storage/filesystem.py", line 106, in _save
web-1  |     fd = os.open(full_path, self.OS_OPEN_FLAGS, 0o666)
web-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  | PermissionError: [Errno 13] Permission denied: '/home/wger/static/CACHE/js/output.a09f97dc7021.js'
web-1  | 
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/axes/middleware.py", line 47, in __call__
web-1  |     response = self.get_response(request)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 57, in inner
web-1  |     response = response_for_exception(request, exc)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 143, in response_for_exception
web-1  |     log_response(
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/utils/log.py", line 241, in log_response
web-1  |     getattr(logger, level)(
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1568, in error
web-1  |     self._log(ERROR, msg, args, **kwargs)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
web-1  |     self.handle(record)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
web-1  |     self.callHandlers(record)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
web-1  |     hdlr.handle(record)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
web-1  |     self.emit(record)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/utils/log.py", line 128, in emit
web-1  |     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/utils/log.py", line 131, in send_mail
web-1  |     mail.mail_admins(
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/mail/__init__.py", line 124, in mail_admins
web-1  |     raise ValueError("The ADMINS setting must be a list of 2-tuples.")
web-1  | ValueError: The ADMINS setting must be a list of 2-tuples.
```
The following error block keeps on repeating itself throughout the logs after startup.
```
web-1  | During handling of the above exception, another exception occurred:
web-1  | 
web-1  | Traceback (most recent call last):
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
web-1  |     response = get_response(request)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/axes/middleware.py", line 47, in __call__
web-1  |     response = self.get_response(request)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 57, in inner
web-1  |     response = response_for_exception(request, exc)
web-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 143, in response_for_exception
web-1  |     log_response(
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/utils/log.py", line 241, in log_response
web-1  |     getattr(logger, level)(
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1568, in error
web-1  |     self._log(ERROR, msg, args, **kwargs)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
web-1  |     self.handle(record)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
web-1  |     self.callHandlers(record)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
web-1  |     hdlr.handle(record)
web-1  |   File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
web-1  |     self.emit(record)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/utils/log.py", line 128, in emit
web-1  |     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/utils/log.py", line 131, in send_mail
web-1  |     mail.mail_admins(
web-1  |   File "/home/wger/.local/lib/python3.12/site-packages/django/core/mail/__init__.py", line 124, in mail_admins
web-1  |     raise ValueError("The ADMINS setting must be a list of 2-tuples.")
web-1  | ValueError: The ADMINS setting must be a list of 2-tuples.
``` 

My docker-compose.yml:
```
services:
  web:
    image: wger/server:latest
    depends_on:
      db:
        condition: service_healthy
      cache:
           condition: service_healthy
    env_file: "wger.env"
    volumes:
      - custompath/to/wger/static/:/home/wger/static
      #- custompath/to/wger/media/:/home/wger/media
    expose:
      - 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped
    networks:
       - default
      
  nginx:
    image: nginx:stable
    depends_on:
      - web
    volumes:
      - custompath/to/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - custompath/to/wger/static/:/wger/static:ro
      - custompath/to/wger/media/:/wger/media:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.wger.entrypoints: "websecure"
      traefik.http.routers.wger.rule: "Host(`wger.mypage.tld`)"
      traefik.http.routers.wger.tls: "true"
      traefik.http.routers.wger.tls.certresolver: "http_resolver"
      traefik.http.routers.wger.service: "wger"
      traefik.http.services.wger.loadbalancer.server.port: "80"
      traefik.docker.network: "proxy"
      traefik.http.routers.wger.middlewares: "default@file"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - proxy
      - default

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
      - POSTGRES_DB=${DJANGO_DB_DATABASE}
    volumes:
      - custompath/to/data/:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U ${DJANGO_DB_USER}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default

  cache:
    image: redis
    expose:
      - 6379
    volumes:
      - custompath/to/wger/redis/:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - default
      
networks:
  proxy:
    external: true
```
my .env:
```
# Django's secret key, change to a 50 character random string if you are running this instance publicly.
SECRET_KEY=secretkey

# Signing key used for JWT, use something different than the secret key
SIGNING_KEY=signinkey

TIME_ZONE=Europe/Berlin

# Consult the deployment section in the readme if you are running this behind a reverse proxy with HTTPS enabled

CSRF_TRUSTED_ORIGINS=https://wger.mydomain.tld,http://wger.mydomain.tld
# X_FORWARDED_PROTO_HEADER_SET=True 
#
# Static files
# If you are running the application behind a reverse proxy or changed the port, the links for some images *might* break (specially in the mobile app).
# Also note that the API response is cached and contains the host, if you change this setting, just run
# docker compose exec web python3 manage.py warmup-exercise-api-cache --force
MEDIA_URL=https://wger.mydomain.tld/media/
STATIC_URL=https://wger.mydomain.tld/static/
#
# These settings usually don't need changing
#
# Application
WGER_INSTANCE=https://wger.de #Wger instance from which to sync exercises, images, etc.
ALLOW_REGISTRATION=False
ALLOW_GUEST_USERS=False
ALLOW_UPLOAD_VIDEOS=True
# Users won't be able to contribute to exercises if their account age is lower than this amount in days.
MIN_ACCOUNT_AGE_TO_TRUST=0
# Synchronzing exercises
# It is recommended to keep the local database synchronized with the wger instance specified in WGER_INSTANCE since there are new added or translations improved.
# For this you have different possibilities:
# - Sync exercises on startup:
SYNC_EXERCISES_ON_STARTUP=False
DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP=False
# - Sync them in the background with celery.
#   This will setup a job that will run once a week at a random time (this time is selected once when starting the server)
#SYNC_EXERCISES_CELERY=False
#SYNC_EXERCISE_IMAGES_CELERY=False
#SYNC_EXERCISE_VIDEOS_CELERY=False
# - Manually trigger the process as needed:
DJANGO_ADMINS=admin@mail.tld
```
