### ISSUE TITLE
Traefik + Nginx Proxy in Unraid

### ISSUE THREAD

**Issue by Theviki20110** [wger-project/docker#115]
Hi everyone,

I’ve been trying to deploy Wger on my Unraid server, but when I attempt to connect, I get a “Gateway Timeout” error from Traefik. After checking the Traefik logs, I found the following:

` 504 Gateway Timeout error="dial tcp 10.0.5.5:80: i/o timeout"
`

10.0.5.5 is the Nginx container’s IP address

Here is my docker-compose.yml:

```
services:
  wger:
    image: wger/server:latest
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ./config/prod.env
    volumes:
      - /mnt/user/appdata/wger/static:/home/wger/static
      - /mnt/user/appdata/wger/media:/home/wger/media
    expose:
      - 8000
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped
    networks:
      - wger_network

  nginx:
    image: nginx:stable
    depends_on:
      - wger
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /mnt/user/appdata/wger/static:/home/wger/static:ro
      - /mnt/user/appdata/wger/media:/home/wger/media:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wger.rule=Host(`wger.example.com`)"
      - "traefik.http.routers.wger.entrypoints=websecure"
      - "traefik.http.routers.wger.tls=true"
      - "traefik.http.routers.wger.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wger.service=wger"
      - "traefik.http.services.wger.loadbalancer.server.port=80"
      - "traefik.docker.network=wger_network"
     # - "traefik.http.routers.wger.middlewares=default@file"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - wger_network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=foo
      - POSTGRES_PASSWORD=foo
      - POSTGRES_DB=foo
    volumes:
      - /mnt/user/appdata/wger/postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - wger_network

  cache:
    image: redis
    expose:
      - 6379
    volumes:
      - /mnt/user/appdata/wger/redis-data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - wger_network

  celery_worker:
    image: wger/server:latest
    command: /start-worker
    env_file:
      - ./config/prod.env
    volumes:
      - /mnt/user/appdata/wger/media:/home/wger/media
    depends_on:
      wger:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wger_network

  celery_beat:
    image: wger/server:latest
    command: /start-beat
    volumes:
      - /mnt/user/appdata/wger/celery-beat:/home/wger/beat/
    env_file:
      - ./config/prod.env
    depends_on:
      celery_worker:
        condition: service_healthy
    networks:
      - wger_network

networks:
  wger_network:
    name: wger_network
    external: true
```

And this is my .env file:

```
SECRET_KEY=stuff

SIGNING_KEY=stuff


TIME_ZONE=Europe/Berlin

MEDIA_URL=https://wger.example.com/media/
STATIC_URL=https://wger.example.com/static/


WGER_INSTANCE=https://wger.de # Wger instance from which to sync exercises, images, etc.
ALLOW_REGISTRATION=True
ALLOW_GUEST_USERS=True
ALLOW_UPLOAD_VIDEOS=True


MIN_ACCOUNT_AGE_TO_TRUST=21


SYNC_EXERCISES_CELERY=True
SYNC_EXERCISE_IMAGES_CELERY=True
SYNC_EXERCISE_VIDEOS_CELERY=True


SYNC_INGREDIENTS_CELERY=True

DOWNLOAD_INGREDIENTS_FROM=WGER

USE_CELERY=True

CELERY_BROKER=redis://cache:6379/2
CELERY_BACKEND=redis://cache:6379/2
CELERY_FLOWER_PASSWORD=adminadmin

DJANGO_DB_ENGINE=django.db.backends.postgresql
DJANGO_DB_DATABASE=wger
DJANGO_DB_USER=wger
DJANGO_DB_PASSWORD=wger
DJANGO_DB_HOST=db
DJANGO_DB_PORT=5432
DJANGO_PERFORM_MIGRATIONS=True # Perform any new database migrations on startup


DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
DJANGO_CACHE_LOCATION=redis://cache:6379/1
DJANGO_CACHE_TIMEOUT=1296000 # in seconds - 60*60*24*15, 15 Days
DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient

AXES_ENABLED=True
AXES_FAILURE_LIMIT=10
AXES_COOLOFF_TIME=30 # in minutes
AXES_HANDLER=axes.handlers.cache.AxesCacheHandler
AXES_LOCKOUT_PARAMETERS=ip_address
AXES_IPWARE_PROXY_COUNT=1
AXES_IPWARE_META_PRECEDENCE_ORDER=HTTP_X_FORWARDED_FOR,REMOTE_ADDR


DJANGO_DEBUG=False
WGER_USE_GUNICORN=True
EXERCISE_CACHE_TTL=18000 # in seconds - 5*60*60, 5 hours
SITE_URL=https://wger.example.com

ACCESS_TOKEN_LIFETIME=10 # The lifetime duration of the access token, in minutes
REFRESH_TOKEN_LIFETIME=24 # The lifetime duration of the refresh token, in hours

USE_RECAPTCHA=False

DJANGO_CLEAR_STATIC_FIRST=False

NUMBER_OF_PROXIES=1
```

I would really appreciate any feedback or suggestions on how to resolve this issue.

Thanks a lot!

**Comment by Theviki20110** [comment]
I share the [solution](https://stackoverflow.com/questions/45187330/traefik-with-docker-networks
)
I was deploying wger on a different docker network.

**Comment by rolandgeider** [comment]
hi! so it's possible to use a compose file in unraid? the current unraid config we have was contributed by someone from the communits, hasn't been updated since and doesn't really work anymore. I'll point people to this issue if they run into problems

**Comment by Theviki20110** [comment]
Sure! You can use docker compose plugin as well. I've also seen that config but It was outdated.
Another point: I've had trouble with static resources and I've noticed that nginx was trying to find them in:

```
location /static/ {
        alias /wger/static/;
    }
```

But it should be changed to `alias /home/wger/static/;` according to docker-compose.yml: 

```
nginx:
    image: nginx:stable
    depends_on:
      - wger
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /mnt/user/appdata/wger/static:/home/wger/static:ro
      - /mnt/user/appdata/wger/media:/home/wger/media:ro
```
