### ISSUE TITLE
Please help - I f*ed up - Database upgrade

### ISSUE THREAD

**Issue by SuperDarius-git** [wger-project/docker#123]
Good day

I recently upgraded my wger instance (Docker) and the logs said I must upgrade my postgres database to 14 or above. It was 12. I didn't realize the database didn't upgrade together with the server. Now I changed the Docker-Compose file by adding some missing lines I saw missing compared to the compose file on here. I will post my new docker-compose file below. 

I desperately need to get old data to persist. I can't delete the volume so that the old data is gone.

This is what the logs are showing now: 

```
2025-04-28 18:20:23.369 UTC [1] FATAL:  database files are incompatible with server

2025-04-28 18:20:23.369 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.12.
```

Here is my compose file:

```
services:
  web:
    image: wger/server:latest
    container_name: wger_server
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ./config/prod.env
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
      # For development, mount your local git checkout
      # - type: bind
      #  source: /path/to/wger/sourcecode
      #  target: /home/wger/src/
    ports:
      - "8000:8000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: wger_nginx
    depends_on:
      - web
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/wger/static:ro
      - media:/wger/media:ro
    ports:
      - "830:80"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: wger_db
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=########
      - POSTGRES_DB=wger
      - TZ=Africa/Johannesburg
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cache:
    image: redis
    container_name: wger_cache
    expose:
      - 6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
#    mem_limit: 5gb
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  celery_worker:
    image: wger/server:latest
    command: /start-worker
    env_file:
      - ./config/prod.env
    volumes:
      - media:/home/wger/media
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: celery -A wger inspect ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  celery_beat:
    image: wger/server:latest
    command: /start-beat
    volumes:
      - celery-beat:/home/wger/beat/
    env_file:
      - ./config/prod.env
    depends_on:
      celery_worker:
        condition: service_healthy

volumes:
  postgres-data:
  celery-beat:
  redis-data:

  # Heads up, if you remove these volumes and use folders directly you need to chown them
  # to the UID and GID 1000 even if it doesn't exist on your system. Also, they should
  # be readable by everyone.
  media:
  static:

networks:
  default:
    name: wger_network
```

This is what the feedback says when trying to up the compose file:

```
[+] Running 4/4
 ✔ Container wger_cache   Healthy                                                                                                                           12.8s 
 ✔ Container wger_server  Created                                                                                                                           10.8s 
 ✘ Container wger_db      Error                                                                                                                              2.2s 
 ✔ Container wger_nginx   Running                                                                                                                            0.0s 
dependency failed to start: container wger_db is unhealthy
```
