### ISSUE TITLE
webgui images "Not Found"

### ISSUE THREAD

**Issue by BadCo-NZ** [wger-project/docker#17]
Hi, I have had wger working in a previous docker install, but I am having trouble re-instating it in a new VM.

Container seems to start fine.
![image](https://user-images.githubusercontent.com/50016048/148641988-d107df57-7efc-40ab-8068-dba5299c4a60.png)

Then when I open the webui, non of the images are displayed and I get these errors in the logs.
![image](https://user-images.githubusercontent.com/50016048/148642211-a9f753f9-d70b-49fd-98ff-f1133bed1f91.png)

![image](https://user-images.githubusercontent.com/50016048/148642053-7512fdbb-a84d-440e-8447-ca880aff83b1.png)

Checking the volumes and the images are there.
![image](https://user-images.githubusercontent.com/50016048/148642164-c63bd755-5651-43cf-a981-e02c055ad910.png)

My docker compose:
```
version: '3.7'

services:
  web:
    restart: always
    image: wger/server:latest
    volumes:
      - /var/lib/docker/volumes/wger_static:/home/wger/static:rw
      - /var/lib/docker/volumes/wger_media:/home/wger/media:rw
    ports:
      - 8084:8000
#    env_file:
#      - ./.prod.env # cannot figure out how to get .env files to be pulled by portainer
    environment:
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_DATABASE=wger
      - DJANGO_DB_USER=wger
      - DJANGO_DB_PASSWORD=wger
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
      - DJANGO_CACHE_LOCATION=redis://cache:6379/1
      - DJANGO_CACHE_TIMEOUT=1296000 # 60*60*24*15, 15 Days
      - DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient
      - DJANGO_MEDIA_ROOT=/home/wger/media
      - SECRET_KEY= wger-docker-secret-key # Change the secret key to a random string if you are running this instance publicly
      - ALLOW_REGISTRATION=True
      - ALLOW_GUEST_USERS=False
      - FROM_EMAIL=admin@domain.tld  # The 'from' address used when sending emails
      - DJANGO_DEBUG=False
      - WGER_USE_GUNICORN=True
      - TIME_ZONE=UTZ
      - SITE_URL=http://localhost:8084
      - ENABLE_EMAIL=True
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_HOST_USER=email@gmail.com
      - EMAIL_HOST_PASSWORD=password
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=True
    depends_on:
      - db
      - cache

#  nginx:
#    build: ./nginx
#    volumes:
#      - static:/wger/static:ro
#      - media:/wger/media:ro
#    ports:
#      - 80:80
#    depends_on:
#      - web

  db:
    restart: always
    image: postgres:12-alpine
    volumes:
      - /var/lib/docker/volumes/wger_postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger

  cache:
    restart: always
    image: redis:latest
    volumes:
      - /var/lib/docker/volumes/wger_redis-data:/data
    expose:
      - 6379
```

Any help would be appreciated :)
