### ISSUE TITLE
Can't start production wger docker

### ISSUE THREAD

**Issue by zero-thermo** [wger-project/docker#39]
I was able to get [wger/apache](https://hub.docker.com/r/wger/apache/#!) up and running since it has a very [straightforward docker-compose](https://gist.github.com/dnburgess/681ca8794457d3d4583985bc535f94f9). However, it doesn't save data and everything is wiped on container restart.  

How do I get the production-ish version up and running if I already have a separate Nginx Proxy Manager for my LAN-only network? Even before setting up a wger reverse proxy, I still can't access via http://PORT:IP.

<details>
  <summary>docker-compose.yaml</summary>

```
version: '3.7'

services:
  web:
    image: wger/server:latest
    container_name: wger_server
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ./config/prod.env
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
      # For development, mount your local git checkout
      # - type: bind
      #  source: /path/to/wger/sourcecode
      #  target: /home/wger/src/
    ports:
      - "8004:8000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

#  nginx:
#    image: nginx:stable
#    container_name: wger_nginx
#    depends_on:
#      - web
#    volumes:
#      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
#      - static:/wger/static:ro
#      - media:/wger/media:ro
#    ports:
#      - "80:80"
#    healthcheck:
#      test: service nginx status
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    restart: unless-stopped

  db:
    image: postgres:12-alpine
    container_name: wger_db
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: redis
    container_name: wger_cache
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
  static:
  media:

networks:
  default:
    name: nginx_proxy
```

</details>

Above is s the docker-compose I modified by removing the nginx section and changing the web port to `8004:8000`. Starting wger this way results in "An error occurred. Something happened that caused an error." If I set `DJANGO_DEBUG=True`, I see the following:

    connection to server at "db" (172.16.64.15), port 5432 failed: FATAL:  password authentication failed for user "wger"

prod.env and my docker-compose both retain default settings for user, password, and db, so I'm not sure why I'm getting this error. What else can I do to troubleshoot?
