### ISSUE TITLE
Docker compose without ngix (local/LAN use only)?

### ISSUE THREAD

**Issue by nodecentral** [wger-project/docker#42]
Hi,

Please could someone help me with what the Docker compose needs to be for a local/lan only (no ngix) set up?

**Comment by nodecentral** [comment]
![F701D8A4-BBAD-4A8D-8E74-2691F56453A0](https://user-images.githubusercontent.com/4349292/207177897-ccc9006d-b371-47a9-8362-7954b879250a.jpeg)

**Comment by rolandgeider** [comment]
You do need the nginx service! The Django application doesn't serve any static files, you need a different service for that

**Comment by nodecentral** [comment]
Hi @rolandgeider 

Thanks for responding, please could you elaborate a bit more ? 

_I'm new to nginx, but always understood it to be a reverse proxy to gain access to an internal service externally ? (As I use a vpn I always look for things to be local ?)_

**Comment by rolandgeider** [comment]
So the django application will only serve the application itself (so only the generated html), no static files at all for performance reasons. For this you need something else that does that, on this case an nginx. Technically it also serves as a reverse proxy because it hides the application so that it looks like everything is coming from one placeAm 13.12.2022 06:17 schrieb Node Central ***@***.***>:
Hi @rolandgeider
Thanks for responding, please could you elaborate a bit more ?
I'm new to nginx, but always understood it to be a reverse proxy to gain access to an internal service externally ? (As I use a vpn I always look for things to be local ?)

**Comment by nodecentral** [comment]
Thanks again @rolandgeider , really appreciate the help and the insight..

I've added the nginx element back into the docker compose and run it again, but sadly nothing seems to have changed I still have a basic text/html UI ? (Any ideas?)

My Compose and nginx.conf are below..

````
version: '3'
services:
  web:
    image: wger/server:latest
    container_name: wger_server
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment: 
      - SECRET_KEY=wger-docker-supersecret-key
      - SIGNING_KEY=wger-docker-secret-jwtkey
      - FROM_EMAIL=node.central@example.com
      - TIME_ZONE=Europe/London
      - ALLOW_REGISTRATION=True
      - ALLOW_GUEST_USERS=True
      - ALLOW_UPLOAD_VIDEOS=True
      - MIN_ACCOUNT_AGE_TO_TRUST=18
      - SYNC_EXERCISES_ON_STARTUP=True
      - DOWNLOAD_EXERCISE_IMAGES_ON_STARTUP=True
      # Database
      - DJANGO_DB_ENGINE=django.db.backends.postgresql
      - DJANGO_DB_DATABASE=wger
      - DJANGO_DB_USER=wger
      - DJANGO_DB_PASSWORD=wger
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_PERFORM_MIGRATIONS=True
      # Cache
      - DJANGO_CACHE_BACKEND=django_redis.cache.RedisCache
      - DJANGO_CACHE_LOCATION=redis://cache:6379/1
      # 60*60*24*15, 15 Days
      - DJANGO_CACHE_TIMEOUT=12
      - DJANGO_CACHE_CLIENT_CLASS=django_redis.client.DefaultClient
      # Brute force login attacks - https://django-axes.readthedocs.io/en/latest/index.html
      - AXES_ENABLED=True
      - AXES_FAILURE_LIMIT=10
      # in minutes
      - AXES_COOLOFF_TIME=30
      - AXES_HANDLER=axes.handlers.cache.AxesCacheHandler
      # Others
      - DJANGO_DEBUG=False
      - WGER_USE_GUNICORN=True
      - EXERCISE_CACHE_TTL=10
      - SITE_URL=http://localhost
      # JWT auth - The lifetime duration of the access token, in minutes
      - ACCESS_TOKEN_LIFETIME=10
      # The lifetime duration of the refresh token, in hours
      - REFRESH_TOKEN_LIFETIME=24
      # Other possible settings
      # RECAPTCHA_PUBLIC_KEY
      # RECAPTCHA_PRIVATE_KEY
      # NOCAPTCHA
      # https://docs.djangoproject.com/en/4.1/topics/email/#smtp-backend
      # ENABLE_EMAIL
      # EMAIL_HOST
      # EMAIL_PORT
      # EMAIL_HOST_USER
      # EMAIL_HOST_PASSWORD
      # EMAIL_USE_TLS
      # EMAIL_USE_SSL
      # DJANGO_MEDIA_ROOT
      # DJANGO_STATIC_ROOT
    volumes:
      - /share/Container/wger/static:/home/wger/static
      - /share/Container/wger/media:/home/wger/media
    ports:
      - "8000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable
    container_name: wger_nginx
    depends_on:
      - web
    volumes:
      #- ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /share/Container/wger/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /share/Container/wger/static:/wger/static:ro
      - /share/Container/wger/media:/wger/media:ro
    ports:
      - "8001:80"
    healthcheck:
      test: service nginx status
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db:
    image: postgres:12-alpine
    container_name: wger_db
    environment:
      - POSTGRES_USER=wger
      - POSTGRES_PASSWORD=wger
      - POSTGRES_DB=wger
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    healthcheck:
      test: pg_isready -U wger
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  cache:
    image: redis
    container_name: wger_cache
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
  static:
  media:

networks:
  default:
      name: wger_network
````
And my nginx.conf file is below..
````

upstream wger {
    server web:8000;
}

server {
    listen 80;
    listen [::]:80;

    location / {
        proxy_pass http://localhost:8001;
    }

    # Increase max body size to allow for video uploads
    client_max_body_size 100M;
}
````
