### ISSUE TITLE
dependency failed to start: container wger_server is unhealthy

### ISSUE THREAD

**Issue by Victorivus** [wger-project/docker#82]
I am unable to launch it, all containers get launched except for wger_server. 

After executing the `apt-get install -y libjpeg-turbo8` it just exits.

`dependency failed to start: container wger_server is unhealthy`

```
services:
  web:
    user: root
    image: wger/server:latest
    container_name: wger_server
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    env_file:
      - ./config/prod.env
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
    expose:
      - 8000
    command: apt-get install -y libjpeg-turbo8
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 1000s
      timeout: 5000s
      retries: 5
    restart: unless-stopped
```

Error is:
![Capture d’écran du 2024-03-29 12-25-13](https://github.com/wger-project/docker/assets/18736740/2d5e5f7c-21db-4b9b-aedd-79c5e730e30c)

`docker ps`
![image](https://github.com/wger-project/docker/assets/18736740/c5e0d6df-29b5-479f-b82c-ba36b1e53051)

When relaunching without down, I get: 

![image](https://github.com/wger-project/docker/assets/18736740/3e90ed97-3385-42c5-bccf-dc799f7d898a)

Can someone help me? Let me know if you need more information.

Hardware: `Raspberry Pi 2 Model B Rev 1.1`  (`ARMv7 Processor rev 5 (v7l)`)
OS version: `#1 SMP Raspbian 1:6.6.20-1+rpt1 (2024-03-07)`
