### ISSUE TITLE
`Internal Server Error: /` caused by (?) `psycopg2.OperationalError: could not translate host name "db" to address`

### ISSUE THREAD

**Issue by seyfeb** [wger-project/docker#91]
While trying to run the docker-compose setup I ran into the following error during startup of the server:

```
psycopg2.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution
```
And then in the end

```
ERROR 2024-07-20 18:09:22,684 log Internal Server Error: /
```

Does anyone have an idea what might be the reason for this?

Some details on the setup: I want to run the setup behind traefik as a reverse proxy and did some configuration stuff in the override and custom env files 

<details>

<summary>`docker-compose.override.yml`</summary>

```
services:
  web:
    env_file:
      - ./config/prod.env
      - ./config/wger-local.env
    labels:
      - traefik.docker.network=gateway
      - traefik.enable=true
      - traefik.http.routers.wger.rule=Host(`wger.mydomain.com`)
      - traefik.http.routers.wger.entrypoints=websecure
      - traefik.http.routers.wger.tls=true
      - traefik.http.routers.wger.tls.certresolver=letsencryptresolver
      - traefik.http.routers.wger.tls.domains[0].main=wger.mydomain.com
      - traefik.http.routers.wger.tls.domains[0].sans=wger.mydomain.com
    networks:
      - gateway
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  celery_worker:
    env_file:
      - ./config/prod.env
      - ./config/wger-local.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  celery_beat:
    env_file:
      - ./config/prod.env
      - ./config/wger-local.env
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

# Prevent nginx from being started as we are using traefik as reverse proxy
  nginx:
    deploy:
      replicas: 0

  db:
    environment:
      - POSTGRES_PASSWORD=wg3r
    volumes:
      - "/etc/localtime:/etc/localtime:ro"


# Mount volumes on disk for backip
volumes:
  postgres-data:
    driver_opts:
      type: none
      device: /hosting/wger/postgres-data
      o: bind
  media:
    driver_opts:
      type: none
      device: /hosting/wger/media
      o: bind

# Add traefik network
networks:
  gateway:
    external: true
```
</details>

<details>

<summary>`wger-local.env`</summary>

```
ALLOW_REGISTRATION=False
ALLOW_GUEST_USERS=False

# Users won't be able to contribute to exercises if their account age is
# lower than this amount in days.
MIN_ACCOUNT_AGE_TO_TRUST=0


SECRET_KEY="XXX"
SIGNING_KEY="XXX"


DJANGO_DB_PASSWORD=wg3r

SITE_URL=https://wger.mydomain.com


#
# Consult the deployment section in the readme if you are running this behind a
# reverse proxy with HTTPS enabled
CSRF_TRUSTED_ORIGINS=https://wger.mydomain.com,https://89.58.63.94
X_FORWARDED_PROTO_HEADER_SET=True

#
# Static files
# If you are running the application behind a reverse proxy or changed the port, the
# links for some images *might* break (specially in the mobile app). Also note that
# the API response is cached and contains the host, if you change this setting, just run
# docker compose exec web python3 manage.py warmup-exercise-api-cache --force
MEDIA_URL=https://wger.mydomain.com/media/
STATIC_URL=https://wger.mydomain.com/static/

#
# Celery
CELERY_FLOWER_PASSWORD=XXX

# Email
# https://docs.djangoproject.com/en/4.1/topics/email/#smtp-backend
ENABLE_EMAIL=True
EMAIL_HOST=mail.mydomain.com
EMAIL_PORT=587
EMAIL_HOST_USER=services@mydomain.com
EMAIL_HOST_PASSWORD=XXX
EMAIL_USE_TLS=True
EMAIL_USE_SSL=False
FROM_EMAIL='wger Workout Manager <services@mydomain.com>'

# Set your name and email to be notified if an internal server error occurs.
# Needs a working email configuration
DJANGO_ADMINS=XXX,admin+wger@mydomain.com
```
</details>

<details>

<summary>Error trace</summary>

```
wger_server  | Successfully installed wger-2.3.0a2
wger_server  | INFO 2024-07-20 17:53:33,640 apps AXES: BEGIN version 6.5.1, blocking by ip_address
wger_server  | *** Database does not exist, creating one now
wger_server  | Traceback (most recent call last):
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 289, in ensure_connection
wger_server  |     self.connect()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
wger_server  |     return func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 270, in connect
wger_server  |     self.connection = self.get_new_connection(conn_params)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
wger_server  |     return func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
wger_server  |     connection = self.Database.connect(**conn_params)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
wger_server  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
wger_server  | psycopg2.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution
wger_server  |
wger_server  |
wger_server  | The above exception was the direct cause of the following exception:
wger_server  |
wger_server  | Traceback (most recent call last):
wger_server  |   File "/usr/local/bin/invoke", line 8, in <module>
wger_server  |     sys.exit(program.run())
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 398, in run
wger_server  |     self.execute()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/program.py", line 583, in execute
wger_server  |     executor.execute(*self.tasks)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/executor.py", line 140, in execute
wger_server  |     result = call.task(*args, **call.kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/tasks.py", line 138, in __call__
wger_server  |     result = self.body(*args, **kwargs)
wger_server  |   File "/home/wger/src/wger/tasks.py", line 90, in bootstrap
wger_server  |     migrate_db(context, settings_path=settings_path)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/tasks.py", line 138, in __call__
wger_server  |     result = self.body(*args, **kwargs)
wger_server  |   File "/home/wger/src/wger/tasks.py", line 210, in migrate_db
wger_server  |     call_command('migrate')
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 194, in call_command
wger_server  |     return command.execute(*args, **defaults)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 458, in execute
wger_server  |     output = self.handle(*args, **options)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 106, in wrapper
wger_server  |     res = handle_func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 117, in handle
wger_server  |     executor = MigrationExecutor(connection, self.migration_progress_callback)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 18, in __init__
wger_server  |     self.loader = MigrationLoader(self.connection)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 58, in __init__
wger_server  |     self.build_graph()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/loader.py", line 235, in build_graph
wger_server  |     self.applied_migrations = recorder.applied_migrations()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 81, in applied_migrations
wger_server  |     if self.has_table():
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/recorder.py", line 57, in has_table
wger_server  |     with self.connection.cursor() as cursor:
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
wger_server  |     return func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 330, in cursor
wger_server  |     return self._cursor()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 306, in _cursor
wger_server  |     self.ensure_connection()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
wger_server  |     return func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 288, in ensure_connection
wger_server  |     with self.wrap_database_errors:
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
wger_server  |     raise dj_exc_value.with_traceback(traceback) from exc_value
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 289, in ensure_connection
wger_server  |     self.connect()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
wger_server  |     return func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/base.py", line 270, in connect
wger_server  |     self.connection = self.get_new_connection(conn_params)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/utils/asyncio.py", line 26, in inner
wger_server  |     return func(*args, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
wger_server  |     connection = self.Database.connect(**conn_params)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
wger_server  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
wger_server  | django.db.utils.OperationalError: could not translate host name "db" to address: Temporary failure in name resolution
wger_server  |
wger_server  | Traceback (most recent call last):
wger_server  |   File "/home/wger/.local/bin/wger", line 8, in <module>
wger_server  |     sys.exit(main())
wger_server  |   File "/home/wger/src/wger/__main__.py", line 40, in main
wger_server  |     run(invoke_cmd + ' '.join(args), pty=True)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/__init__.py", line 50, in run
wger_server  |     return Context().run(command, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/context.py", line 104, in run
wger_server  |     return self._run(runner, command, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/context.py", line 113, in _run
wger_server  |     return runner.run(command, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/runners.py", line 395, in run
wger_server  |     return self._run_body(command, **kwargs)
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/runners.py", line 451, in _run_body
wger_server  |     return self.make_promise() if self._asynchronous else self._finish()
wger_server  |   File "/usr/local/lib/python3.10/dist-packages/invoke/runners.py", line 518, in _finish
wger_server  |     raise UnexpectedExit(result)
wger_server  | invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
wger_server  |
wger_server  | Command: 'invoke bootstrap'
wger_server  |
wger_server  | Exit code: 1
```
</details>
